config/routes.rb
Rails.application.routes.draw do
  root 'games#index'
  resources :scores
  resources :teams

  resources :games do
    post 'generate_result', on: :collection
    post 'generate_play_off_games_with_results', on: :collection
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  
  scope :division_a, -> { where(division: 'A') }
  scope :division_b, -> { where(division: 'B') }
  scope :play_off, -> { where(division: 'P') }
  
  has_many :scores
  
  belongs_to :first_team, class_name: 'Team', foreign_key: "team_a"
  belongs_to :second_team, class_name: 'Team', foreign_key: "team_b"
 
  
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :game
  belongs_to :team 
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :scores

  scope :division_a, -> { where(division: 'A') }
  scope :division_b, -> { where(division: 'B') }

  #attr_accessor :division_game_points
    
  def division_games(game_type)
    Game.where("(team_a = ? or team_b = ?) and game_type = ?", id, id, game_type)
  end
  
  def division_games_results(game_type)
    division_games(game_type).map{|game| game.scores}.flatten 
  end
  
  def division_games_points(game_type)
    division_games_results(game_type).map{|score| score.point if score.team_id == id}.compact 
  end
  
  def division_game_result(division, team_a, team_b)
    if team_a == team_b
      return "- : -"
    else
      game = Game.where("game_type = ? and ( (team_a = ? and team_b = ?) or (team_a = ? and team_b = ?) )", division, team_a, team_b, team_b, team_a).first
      if game
        score = Score.where(game_id: game.id, team_id: team_a).first
        if score
          return score.score
        end
      else 
        retun ' : '
      end
      
    end
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @a_division_teams = Team.division_a
    @b_division_teams = Team.division_b
    
    @best_a_division_teams = get_team_list_ordered_by_result(@a_division_teams, 'A')
    @best_b_division_teams = get_team_list_ordered_by_result(@b_division_teams, 'B')

#    @best_all_teams << @best_a_division_teams 
#    @best_all_teams << @best_b_division_teams
  end

   def generate_result
    division = params[:division]
    games = Game.where(game_type: division)
    
    games.each { |game|
      if !game.scores.exists?
        a_game_point = rand(0 .. 9)
        b_game_point = rand(0 .. 9)
        Score.create(team_id: game.team_a, game_id: game.id, score: "#{a_game_point} : #{b_game_point}" , point: a_game_point == b_game_point ? 1 : a_game_point > b_game_point ? 3 : 0)
        Score.create(team_id: game.team_b, game_id: game.id, score: "#{b_game_point} : #{a_game_point}", point: a_game_point == b_game_point ? 1 : b_game_point > a_game_point ? 3 : 0)      
      end 
          
    } 
    
    respond_to do |format|
      format.html { redirect_to games_url, notice: "Results for division #{division} successfully generated." }
      format.json { head :no_content }
    end
    
  end
  
   def generate_play_off_games_with_results
     @best_division_teams = @best_a_division_teams + @best_b_division_teams
     @best_division_teams = @best_division_teams.sort{|a, b| a.division_games_points(a.game_type).sum <=> b.division_games_points(b.game_type).sum }.reverse!
      Rails.logger.info  @best_division_teams.inspect
#     while(@best_division_teams.size > 0)
#      Game.create(game_type: 'P', team_a: @best_a_division_teams.shift.id, team_b: @best_a_division_teams.shift.id) 
#      Game.create(game_type: 'P', team_a: @best_a_division_teams.shift.id, team_b: @best_a_division_teams.pop.id) 
#     end
   end
  
   private 
   
   def get_team_list_ordered_by_result(division_teams, game_type)
    ordered_division_teams = division_teams.sort {|a, b| a.division_games_points(game_type).sum <=> b.division_games_points(game_type).sum }.reverse!
    return ordered_division_teams.take(4)
     
   end
 
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:team_id, :game_id, :score, :point)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:id, :name, :division)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :game_type %>
    <%= form.text_field :game_type, id: :game_game_type %>
  </div>

  <div class="field">
    <%= form.label :team_a %>
    <%= form.number_field :team_a, id: :game_team_a %>
  </div>

  <div class="field">
    <%= form.label :team_b %>
    <%= form.number_field :team_b, id: :game_team_b %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_playoff_game.html.erb
<%#*<div style="display: inline-block;">%>
  <%#*<table style="border:1px solid #ccc; padding:10px;">%>
    <%#*<tr>%>
      <%#*<td td style="border-bottom:1px solid #ccc; padding:5px;">Play Off</td>%>
    <%#*</tr>%>

    <%# @best_all_teams.each do |team| %>
      <%#*<tr>%>
        <%#*<td td style="border-bottom:1px solid #ccc; padding:5px;"><%= team.name%> </td>%>
        <%#*<td style="border-bottom:1px solid #ccc; padding:5px;"><b><%= team.division_games_points_sum('B') %></b>  </td>%> 
      <%#*</tr>%>
<%#*e%>
    <%# end %>
  <%#*</table>%>
<%#*</div>%> 

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<div>

  <h1>Games in A Division</h1>

  <table style="border:1px solid #ccc; padding:10px;">
    <tr >
      <td></td>
      <% @a_division_teams.each do |team| %>
        <td style="border-bottom:1px solid #ccc; padding:5px;"><%= team.name%> </td>
      <% end %>
      <td style="border-bottom:1px solid #ccc; padding:5px;">Points </td>
    </tr>

    <% @a_division_teams.each do |row_team| %>
      <tr>
        <td style="border-right:1px solid #ccc; padding:5px;"><%= row_team.name%> </td>
        <% @a_division_teams.each do |column_team| %>
          <td style="text-align: center" >
            <%= row_team.division_game_result('A', row_team.id, column_team.id) %>
          </td>
        <% end %>
        <td style="border-left:1px solid #ccc; padding:5px;"><b> <%= row_team.division_games_points('A').sum %></b> </td>
      </tr>
    <% end %>
  </table>  
  <br/>
  <%= button_to "Generate A division Result", {controller: 'games', action: 'generate_result', division: 'A'}  %>

</div>

<div>

  <h1>Games in B Division</h1>

  <table style="border:1px solid #ccc; padding:10px;">
    <tr>
      <td></td>
      <% @b_division_teams.each do |team| %>
        <td td style="border-bottom:1px solid #ccc; padding:5px;"><%= team.name%> </td>
      <% end %>
      <td style="border-bottom:1px solid #ccc; padding:5px;">Points </td>
    </tr>
    <% @b_division_teams.each do |row_team| %>
      <tr>
        <td style="border-right:1px solid #ccc; padding:5px;"><%= row_team.name%> </td>
        <% @b_division_teams.each do |column_team| %>   
          <td style="text-align: center" >
            <%= row_team.division_game_result('B', row_team.id, column_team.id) %>
          </td>
        <% end %>
        <td style="border-left:1px solid #ccc; padding:5px;"><b> <%= row_team.division_games_points('B').sum %> </b></td>
      </tr>

    <% end %>

  </table>
  <br/>
  <%= button_to "Generate B division Result", {controller: 'games', action: 'generate_result', division: 'B'}  %>


  <% if @best_a_division_teams.size > 0 %>
    <h1>Best Teams</h1>

    <div style="display: inline-block; ">
      <table style="border:1px solid #ccc; padding:10px;">
        <tr>
          <td td style="border-bottom:1px solid #ccc; padding:5px;">A Division </td>
        </tr>

        <% @best_a_division_teams.each do |team| %>
          <tr>
            <td td style="border-bottom:1px solid #ccc; padding:5px;"><%= team.name%> </td>
            <td style="border-bottom:1px solid #ccc; padding:5px;"><b><%= team.division_games_points('A').sum %> </b> </td> 
          </tr>

        <% end %>
      </table>
    </div>

    <div style="display: inline-block;">
      <table style="border:1px solid #ccc; padding:10px;">
        <tr>
          <td td style="border-bottom:1px solid #ccc; padding:5px;">B Division </td>
        </tr>

        <% @best_b_division_teams.each do |team| %>
          <tr>
            <td td style="border-bottom:1px solid #ccc; padding:5px;"><%= team.name%> </td>
            <td style="border-bottom:1px solid #ccc; padding:5px;"><b><%= team.division_games_points('B').sum %></b>  </td> 
          </tr>

        <% end %>
      </table>
    </div>    
  <% end %></div>
<br>

<%= button_to "Generate Play Off plays and results", {controller: 'games', action: 'generate_play_off_games_with_results'}  %>

<%= render 'playoff_game' %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game type:</strong>
  <%= @game.game_type %>
</p>

<p>
  <strong>Team a:</strong>
  <%= @game.team_a %>
</p>

<p>
  <strong>Team b:</strong>
  <%= @game.team_b %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TournamentSchedule</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scores/_form.html.erb
<%= form_with(model: score, local: true) do |form| %>
  <% if score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.number_field :team_id, id: :score_team_id %>
  </div>

  <div class="field">
    <%= form.label :game_id %>
    <%= form.number_field :game_id, id: :score_game_id %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.text_field :score, id: :score_score %>
  </div>

  <div class="field">
    <%= form.label :point %>
    <%= form.number_field :point, id: :score_point %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scores</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Game</th>
      <th>Score</th>
      <th>Point</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= score.team_id %></td>
        <td><%= score.game_id %></td>
        <td><%= score.score %></td>
        <td><%= score.point %></td>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>

app/views/scores/new.html.erb
<h1>New Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @score.team_id %>
</p>

<p>
  <strong>Game:</strong>
  <%= @score.game_id %>
</p>

<p>
  <strong>Score:</strong>
  <%= @score.score %>
</p>

<p>
  <strong>Point:</strong>
  <%= @score.point %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>